export {
  fetchAllTeams,
  fetchTeamWithMembers,
  createTeam,
  updateTeam,
  deleteTeam,
  addTeamMember,
  removeTeamMember,
  fetchTeamsForSelect,
  fetchUsersForSelect,
  findUserByEmail,
  type Team,
  type TeamMember,
  type TeamWithMembers,
  type UserSearchResult,
} from './teams.service';
